title: 40 en fit, Training , Livestyle, Food, Gear, Reviews en Events
description: > # this means to ignore newlines until "baseurl:"
  Plots was ik 40 jaar en was ik half zo fit als ik wilde zijn. Dat moest veranderen. Mijn blog gaat over mijn 40+ leven en vooral hoe ik fit probeer te blijven
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

excerpt_separator: < !--more -->

# Author Settings
author: Theo van der Sluijs # add your name
author-img: https://nl.gravatar.com/userimage/4342738/55dc66ed50cf30a99a5c12767dae233a.jpg?size=400 # add your photo
about-author: Als een developer, manager, (agile) coach en als liefhebber van het bourgondische probeer ik ook nog eens gezond te leven. # add description
social-twitter: tvdsluijs
#social-facebook: # add your Facebook handle
social-github: tvdsluijs # add your Github handle
social-linkedin: tvandersluijs
social-email: tvdsluijs@gmail.com

# Disqus
discus-identifier: # add your discus identifier

# Tracker
google_analytics: UA-1497722-30 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
